version: '2'
services:
  db:
    image: informaticsmatters/rdkit_cartridge 
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db

