version: '2'
services:
  db:
    image: informaticsmatters/rdkit_cartridge 
    ports:
      - "5432:5432"
  web:
    build: .
    command: jupyter notebook --no-browser --port 8888 --allow-root --ip=0.0.0.0 --NotebookApp.token=${TOKEN} --NotebookApp.password=${PASS}
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db

